-- ユーザー本体
CREATE TABLE IF NOT EXISTS users (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    device_id VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(32) NOT NULL DEFAULT 'あいうえお',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_claimed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 認証トークン

-- ユーザーの資源